services:
  backend:
    build: ./challenge-BE
    ports:
      - "8080:8080"
    networks:
      - appnet

  frontend:
    build: ./challenge-FE
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
